name: 新功能
description: 提交一个新功能请求。
title: 新功能请求：<你的报告标题>
labels:
  - enhancement
  - question
assignees:
  - Arondight
body:
  - type: textarea
    id: question
    attributes:
      label: 问题描述
      description: 请在此详细描述你想新增的功能。
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: git-log
    attributes:
      label: 代码状态：最新提交
      description: 请将命令 `git log -1` 的输出结果粘贴在此处。
      render: Text
      placeholder:
    validations:
      required: false
